Upgrade to 2.5, editor in product is not running without JDT
java.lang.IllegalStateException: Missing contribution for type:
org.eclipse.xtext.ui.resource.IStorage2UriMapperJdtExtensions